// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200623142731_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Age = 0,
                            Avatar = "~/images/avatar.png",
                            DOB = new DateTime(2001, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 0,
                            Email = "minh@gmail.com",
                            FullName = "Tôn Thất Anh Minh",
                            Name = "Anh Minh"
                        },
                        new
                        {
                            id = 2,
                            Age = 0,
                            Avatar = "~/images/avatar2.png",
                            DOB = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 1,
                            Email = "Trang@gmail.com",
                            FullName = "Hồ Thị Nhật Trang",
                            Name = "Nhật Trang"
                        },
                        new
                        {
                            id = 3,
                            Age = 0,
                            Avatar = "~/images/avatar2.png",
                            DOB = new DateTime(2001, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 1,
                            Email = "Thanh@gmail.com",
                            FullName = "Văn Vũ Thanh Thanh",
                            Name = "Thanh Thanh"
                        },
                        new
                        {
                            id = 4,
                            Age = 0,
                            Avatar = "~/images/avatar2.png",
                            DOB = new DateTime(2001, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 1,
                            Email = "Tue@gmail.com",
                            FullName = "Dương Gia Tuệ",
                            Name = "Gia Tuệ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
