// <auto-generated />
using System;
using Cinema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200627083727_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.Models.Film", b =>
                {
                    b.Property<string>("filmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("filmDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filmPoster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("timeOfFilm")
                        .HasColumnType("int");

                    b.HasKey("filmId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            filmId = "9308962d-351d-4080-8424-6330f74396bd",
                            filmDescription = "Avengers: Hồi kết là phim điện ảnh siêu anh hùng Mỹ ra mắt năm 2019, do Marvel Studios sản xuất và Walt Disney Studios Motion Pictures phân phối. Phim là phần thứ tư của loạt phim Avengers, sau Biệt đội siêu anh hùng, Avengers: Đế chế Ultron và Avengers: Cuộc chiến vô cực.",
                            filmName = "End Game",
                            filmPoster = "images/endgame.jpg",
                            timeOfFilm = 182
                        },
                        new
                        {
                            filmId = "957ad7cb-1d34-42ee-8b9d-1fe22ca1f6c7",
                            filmDescription = "Chuyến tàu sinh tử là một bộ phim về đại dịch zombie của Hàn Quốc được đạo diễn bởi Yeon Sang-ho với sự tham gia các diễn viên Gong Yoo, Jung Yu-mi và Ma Dong-seok. Bộ phim đã được công chiếu trước tại khu vực Midnight Screenings tại Liên hoan phim Cannes 2016 vào ngày 13 tháng 5.",
                            filmName = "Train to Busan",
                            filmPoster = "images/busan.png",
                            timeOfFilm = 118
                        },
                        new
                        {
                            filmId = "61d0f453-5012-47ad-90b8-7703b6f88b30",
                            filmDescription = "Phi vụ thế kỷ 2 là phim hành động Mỹ được phát hành của Jon M. Chu. Đây là phần tiếp theo của Phi vụ thế kỷ năm 2013, với sự tham gia của Jesse Eisenberg, Mark Ruffalo, Woody Harrelson, Dave Franco, Daniel Radcliffe, Lizzy Caplan, Jay Chou, Sanaa Lathan và 2 diễn viên gạo cội của Anh và Mỹ: Michael Caine và Morgan ...",
                            filmName = "NOW YOU SEE ME 2",
                            filmPoster = "images/nowyouseeme.jpg",
                            timeOfFilm = 130
                        },
                        new
                        {
                            filmId = "0764ecae-677c-4cf7-b796-a603e667631f",
                            filmDescription = "Chơi hay Chết?, là một bộ phim kinh dị siêu nhiên năm 2018 của Mỹ được đạo diễn bởi Jeff Wadlow và được viết bởi Michael Reisz, Jillian Jacobs, Chris Roach và Wadlow.",
                            filmName = "Truth Or Dare",
                            filmPoster = "images/truth.jpg",
                            timeOfFilm = 103
                        });
                });

            modelBuilder.Entity("Cinema.Models.Room", b =>
                {
                    b.Property<string>("roomId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Seatavailable")
                        .HasColumnType("int");

                    b.Property<int>("statusRoom")
                        .HasColumnType("int");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            roomId = "R01",
                            Seatavailable = 50,
                            statusRoom = 0
                        },
                        new
                        {
                            roomId = "R02",
                            Seatavailable = 50,
                            statusRoom = 0
                        },
                        new
                        {
                            roomId = "R03",
                            Seatavailable = 50,
                            statusRoom = 0
                        },
                        new
                        {
                            roomId = "R04",
                            Seatavailable = 50,
                            statusRoom = 0
                        },
                        new
                        {
                            roomId = "R05",
                            Seatavailable = 50,
                            statusRoom = 0
                        });
                });

            modelBuilder.Entity("Cinema.Models.Screening", b =>
                {
                    b.Property<string>("screeningID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("filmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("timeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("timeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("screeningID");

                    b.ToTable("CinemaManagements");
                });

            modelBuilder.Entity("Cinema.Models.Seat", b =>
                {
                    b.Property<string>("seatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("roomId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seatStatus")
                        .HasColumnType("int");

                    b.HasKey("seatId");

                    b.ToTable("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
